In [59]:
import pandas as pd
import numpy as np

df = pd.read_csv('/content/produccion-de-carne-bovina.csv', encoding='latin-1')

df.head()

,pais_id,pais,provincia_id,provincia,departamento_id,departamento,prov_depto,año,mes,modelo,...,ingreso_neto_($/ha),gastos_directos_($/ha),costos_indirectos_($/ha),eficiencia_stock_(%),producción_(kg/ha),destete_(%),carga_(kg/ha),Unnamed: 21,Unnamed: 22,Unnamed: 23
0,32,Argentina,6,Buenos Aires,105,Bolivar,6105,2018,2,buenos aires centro-sudoeste,...,3497,1730,1797,35,117,69,336,NaN,NaN,NaN
1,32,Argentina,6,Buenos Aires,231,Daireaux,6231,2018,2,buenos aires centro-sudoeste,...,3497,1730,1797,35,117,69,336,NaN,NaN,NaN
2,32,Argentina,6,Buenos Aires,203,Coronel Suarez,6203,2018,2,buenos aires centro-sudoeste,...,3497,1730,1797,35,117,69,336,NaN,NaN,NaN
3,32,Argentina,14,Cordoba,42,General San Martin,14042,2018,2,centro cordoba sur,...,4589,2544,1909,36,157,65,436,NaN,NaN,NaN
4,32,Argentina,14,Cordoba,56,Juarez Celman,14056,2018,2,centro cordoba sur,...,4589,2544,1909,36,157,65,436,NaN,NaN,NaN

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2598 entries, 0 to 2597
Data columns (total 24 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   pais_id                   2598 non-null   int64
 1   pais                      2598 non-null   object
 2   provincia_id              2598 non-null   int64
 3   provincia                 2598 non-null   object
 4   departamento_id           2598 non-null   int64
 5   departamento              2598 non-null   object
 6   prov_depto                2598 non-null   int64
 7   año                       2598 non-null   int64
 8   mes                       2598 non-null   int64
 9   modelo                    2598 non-null   object
 10  actividad                 2598 non-null   object
 11  referencia                2598 non-null   object
 12  margen_bruto_($/ha)       2598 non-null   int64
 13  resultado_neto_($/ha)     2598 non-null   int64
 14  ingreso_neto_($/ha)       2598 non-null   int64
 15  gastos_directos_($/ha)    2598 non-null   int64
 16  costos_indirectos_($/ha)  2598 non-null   int64
 17  eficiencia_stock_(%)      2598 non-null   int64
 18  producción_(kg/ha)        2598 non-null   int64
 19  destete_(%)               2598 non-null   int64
 20  carga_(kg/ha)             2598 non-null   int64
 21  Unnamed: 21               0 non-null      float64
 22  Unnamed: 22               0 non-null      float64
 23  Unnamed: 23               41 non-null     float64
dtypes: float64(3), int64(15), object(6)
memory usage: 487.3+ KB

In [46]:
df.isnull().sum()

pais_id                        0
pais                           0
provincia_id                   0
provincia                      0
departamento_id                0
departamento                   0
prov_depto                     0
año                            0
mes                            0
modelo                         0
actividad                      0
referencia                     0
margen_bruto_($/ha)            0
resultado_neto_($/ha)          0
ingreso_neto_($/ha)            0
gastos_directos_($/ha)         0
costos_indirectos_($/ha)       0
eficiencia_stock_(%)           0
producción_(kg/ha)             0
destete_(%)                    0
carga_(kg/ha)                  0
Unnamed: 21                 2598
Unnamed: 22                 2598
Unnamed: 23                 2557
dtype: int64

In [47]:
df.dropna(inplace=True)

In [60]:
df = pd.read_csv('/content/produccion-de-carne-bovina.csv', encoding='latin-1')

df = df.iloc[:, :-3]

display(df.head())
df.info()

,pais_id,pais,provincia_id,provincia,departamento_id,departamento,prov_depto,año,mes,modelo,...,referencia,margen_bruto_($/ha),resultado_neto_($/ha),ingreso_neto_($/ha),gastos_directos_($/ha),costos_indirectos_($/ha),eficiencia_stock_(%),producción_(kg/ha),destete_(%),carga_(kg/ha)
0,32,Argentina,6,Buenos Aires,105,Bolivar,6105,2018,2,buenos aires centro-sudoeste,...,http://www.agroindustria.gob.ar/sitio/areas/bo...,1766,-31,3497,1730,1797,35,117,69,336
1,32,Argentina,6,Buenos Aires,231,Daireaux,6231,2018,2,buenos aires centro-sudoeste,...,http://www.agroindustria.gob.ar/sitio/areas/bo...,1766,-31,3497,1730,1797,35,117,69,336
2,32,Argentina,6,Buenos Aires,203,Coronel Suarez,6203,2018,2,buenos aires centro-sudoeste,...,http://www.agroindustria.gob.ar/sitio/areas/bo...,1766,-31,3497,1730,1797,35,117,69,336
3,32,Argentina,14,Cordoba,42,General San Martin,14042,2018,2,centro cordoba sur,...,http://www.agroindustria.gob.ar/sitio/areas/bo...,2045,136,4589,2544,1909,36,157,65,436
4,32,Argentina,14,Cordoba,56,Juarez Celman,14056,2018,2,centro cordoba sur,...,http://www.agroindustria.gob.ar/sitio/areas/bo...,2045,136,4589,2544,1909,36,157,65,436

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2598 entries, 0 to 2597
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   pais_id                   2598 non-null   int64
 1   pais                      2598 non-null   object
 2   provincia_id              2598 non-null   int64
 3   provincia                 2598 non-null   object
 4   departamento_id           2598 non-null   int64
 5   departamento              2598 non-null   object
 6   prov_depto                2598 non-null   int64
 7   año                       2598 non-null   int64
 8   mes                       2598 non-null   int64
 9   modelo                    2598 non-null   object
 10  actividad                 2598 non-null   object
 11  referencia                2598 non-null   object
 12  margen_bruto_($/ha)       2598 non-null   int64
 13  resultado_neto_($/ha)     2598 non-null   int64
 14  ingreso_neto_($/ha)       2598 non-null   int64
 15  gastos_directos_($/ha)    2598 non-null   int64
 16  costos_indirectos_($/ha)  2598 non-null   int64
 17  eficiencia_stock_(%)      2598 non-null   int64
 18  producción_(kg/ha)        2598 non-null   int64
 19  destete_(%)               2598 non-null   int64
 20  carga_(kg/ha)             2598 non-null   int64
dtypes: int64(15), object(6)
memory usage: 426.4+ KB

In [49]:
df_limpio = df.duplicated().sum()
print(f'Cantidad de duplicados: {df_limpio}')

Cantidad de duplicados: 0

In [62]:
exclusion = ['pais_id', 'provincia_id', 'departamento_id', 'prov_depto', 'año', 'mes']

# Seleccionamos todas las columnas excepto las de la lista anterior
df_filtrado = df.drop(columns=exclusion, errors='ignore')

display(df_filtrado.describe().round(2))

,margen_bruto_($/ha),resultado_neto_($/ha),ingreso_neto_($/ha),gastos_directos_($/ha),costos_indirectos_($/ha),eficiencia_stock_(%),producción_(kg/ha),destete_(%),carga_(kg/ha)
count,2598.00,2598.00,2598.00,2598.00,2598.00,2598.00,2598.00,2598.00,2598.00
mean,1001.08,414.79,1585.56,584.46,586.32,32.76,78.71,-16573.92,209.24
std,725.41,532.00,1344.48,864.81,486.09,9.40,76.29,37264.29,134.13
min,-107.00,-1299.00,205.00,46.00,75.00,20.00,7.00,-99999.00,19.00
25%,477.00,119.00,664.00,137.00,241.00,27.00,28.00,60.00,101.00
50%,645.00,241.00,1013.00,228.00,401.00,31.00,46.00,60.00,182.00
75%,1400.00,750.00,2286.00,423.00,777.00,35.00,92.00,69.00,293.00
max,3148.00,1761.00,5980.00,4424.00,2522.00,59.00,284.00,78.00,492.00

In [63]:
# Cargamos los datos originales
df_limpio = pd.read_csv('/content/produccion-de-carne-bovina.csv', encoding='latin-1')
df_limpio = df_limpio.iloc[:, :-3]

# 1. Los porcentajes (destete, eficiencia) lógicamente deben estar entre 0 y 100
df_limpio = df_limpio[(df_limpio['destete_(%)'] >= 0) & (df_limpio['destete_(%)'] <= 100)]
df_limpio = df_limpio[(df_limpio['eficiencia_stock_(%)'] >= 0) & (df_limpio['eficiencia_stock_(%)'] <= 100)]

# 2. Conservamos pérdidas reales (valores negativos válidos en resultados económicos)
# Aca no filtramos los negativos porque perder de -1299 a 0 $/ha es un escenario real de pérdida.

print(f"Filas antes: {len(df)} | Filas después del filtro lógico: {len(df_limpio)}")

# Mostramos el describe de las variables numéricas con las pérdidas conservadas y sin errores
display(df_limpio.drop(columns=exclusion, errors='ignore').describe().round(2))

Filas antes: 2598 | Filas después del filtro lógico: 2166

,margen_bruto_($/ha),resultado_neto_($/ha),ingreso_neto_($/ha),gastos_directos_($/ha),costos_indirectos_($/ha),eficiencia_stock_(%),producción_(kg/ha),destete_(%),carga_(kg/ha)
count,2166.00,2166.00,2166.00,2166.00,2166.00,2166.00,2166.00,2166.00,2166.00
mean,942.28,497.01,1245.46,303.15,445.32,29.26,52.85,64.88,171.89
std,686.50,454.14,924.98,369.55,321.95,4.48,37.06,5.89,98.20
min,86.00,-33.00,205.00,46.00,75.00,20.00,7.00,50.00,19.00
25%,437.00,140.00,609.00,127.00,231.00,26.00,27.00,60.00,95.00
50%,606.00,271.00,814.00,198.00,359.00,29.00,34.00,65.00,122.00
75%,1399.00,831.00,1727.00,318.00,495.00,33.00,92.00,72.00,276.00
max,2496.00,1502.00,4589.00,2544.00,1909.00,40.00,157.00,78.00,436.00